services:
  front:
    image: product-trial-front:latest
    build:
      context: ./front
    ports:
      - 4200/tcp
  back:
    image: product-trial-back:latest
    build:
      context: ./back
    ports:
      - 5000/tcp
    environment:
      - DATA_DIR=/data
    volumes:
      - back_data:/data
volumes:
  back_data:
