services:
  front:
    image: product-trial-front:latest
    build:
      context: ./front
    ports:
      - 4200:4200
  back:
    image: product-trial-back:latest
    build:
      context: ./back
    ports:
      - 5000:5000
    environment:
      - DATA_DIR=/data
    volumes:
      - back_data:/data
volumes:
  back_data:
