services:
  front:
    image: product-trial-front:dev
    volumes:
      - ./front/src:/usr/src/app/src
      - ./front/angular.json:/usr/src/app/angular.json
      - ./front/tsconfig.json:/usr/src/app/tsconfig.json

  back:
    image: product-trial-back:dev
    build:
      target: dev
    volumes:
      - ..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
 
